# Development override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  datascrapexter:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Stop at builder stage for development
    image: datascrapexter:dev
    container_name: datascrapexter-dev
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/bin
      - /app/vendor
    environment:
      - LOG_LEVEL=debug
      - DEBUG=true
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    command: ["go", "run", "./cmd/datascrapexter"]
    stdin_open: true
    tty: true

  # Development database with initialization script
  postgres:
    environment:
      - POSTGRES_DB=datascrapexter_dev
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=devpass
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # Different port to avoid conflicts

  # Mailhog for email testing in development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: datascrapexter-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - datascrapexter-network

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: datascrapexter-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - datascrapexter-network
    depends_on:
      - postgres
