# Real Estate Listings Monitoring Template
# Comprehensive configuration for tracking property listings, prices, and market trends

name: "real-estate-monitor"
version: "1.0"
description: "Real estate market monitoring with property details and price analytics"

# Target configuration for real estate platforms
target:
  url: "${PROPERTY_SEARCH_URL}"
  method: "GET"
  headers:
    User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.9"
    Referer: "${SITE_HOMEPAGE}"

# Session management for search filters
session:
  maintain: true
  cookie_jar: "cookies/real-estate-session.json"

# Request configuration optimized for real estate sites
request:
  timeout: 45
  retry:
    attempts: 3
    delay: 10
    on_status_codes: [429, 500, 502, 503]
  rate_limit:
    requests_per_second: 1
    respect_retry_after: true

# Anti-detection for real estate platforms
antidetect:
  enabled: true
  strategies:
    - randomize_timing: true
      min_delay: 2
      max_delay: 5
    - rotate_user_agents: true
      agents_file: "configs/residential-user-agents.txt"
    - simulate_referrers: true
      referrer_pool:
        - "https://www.google.com/"
        - "https://www.bing.com/"
        - "https://www.zillow.com/"

# Extraction rules for property listings
extraction:
  - name: "property_listings"
    type: "listing"
    container:
      selector: "article.property-card, div.listing-item, .search-result-card"
      multiple: true
    fields:
      - name: "mls_number"
        selector: ".mls-number, .listing-id, [data-mls]"
        type: "text"
        required: true
        transform:
          - type: "extract_pattern"
            pattern: "MLS#?\\s*([A-Z0-9]+)"

      - name: "address"
        selector: ".property-address, .listing-address, address"
        type: "complex"
        components:
          - name: "street"
            selector: ".street-address, .address-line-1"
            type: "text"
          - name: "city"
            selector: ".locality, .city"
            type: "text"
          - name: "state"
            selector: ".region, .state"
            type: "text"
          - name: "zip_code"
            selector: ".postal-code, .zip"
            type: "text"
            transform:
              - type: "validate_pattern"
                pattern: "^\\d{5}(-\\d{4})?$"

      - name: "price"
        selector: ".listing-price, .property-price, [itemprop='price']"
        type: "text"
        required: true
        transform:
          - type: "extract_number"
          - type: "validate_range"
            min: 10000
            max: 100000000

      - name: "price_per_sqft"
        selector: ".price-per-sqft, .ppsf"
        type: "text"
        transform:
          - type: "extract_number"

      - name: "property_type"
        selector: ".property-type, .listing-type"
        type: "text"
        mapping:
          "Single Family": "single_family"
          "Condo": "condominium"
          "Townhouse": "townhouse"
          "Multi Family": "multi_family"
          "Land": "land"
          "Commercial": "commercial"

      - name: "bedrooms"
        selector: ".beds-count, .bedrooms, [data-beds]"
        type: "text"
        transform:
          - type: "extract_number"
          - type: "parse_int"

      - name: "bathrooms"
        selector: ".baths-count, .bathrooms, [data-baths]"
        type: "text"
        transform:
          - type: "extract_number"
          - type: "parse_float"

      - name: "square_feet"
        selector: ".sqft, .square-feet, .living-area"
        type: "text"
        transform:
          - type: "extract_number"
          - type: "parse_int"

      - name: "lot_size"
        selector: ".lot-size, .land-area"
        type: "text"
        transform:
          - type: "extract_number"
          - type: "convert_units"
            from: "auto"
            to: "sqft"

      - name: "year_built"
        selector: ".year-built, .construction-year"
        type: "text"
        transform:
          - type: "extract_number"
          - type: "parse_int"
          - type: "validate_range"
            min: 1800
            max: 2025

      - name: "days_on_market"
        selector: ".dom, .days-on-market"
        type: "text"
        transform:
          - type: "extract_number"
          - type: "parse_int"

      - name: "status"
        selector: ".listing-status, .property-status"
        type: "text"
        mapping:
          "For Sale": "active"
          "Pending": "pending"
          "Contingent": "contingent"
          "Coming Soon": "coming_soon"
          "Sold": "sold"

      - name: "listing_date"
        selector: ".listing-date, time[datetime]"
        attribute: "datetime"
        transform:
          - type: "parse_date"
            format: "auto"

      - name: "images"
        selector: ".property-photos img, .gallery img"
        attribute: "src"
        type: "list"
        transform:
          - type: "absolute_url"
          - type: "extract_high_res"
          - type: "limit"
            max: 25

      - name: "virtual_tour_url"
        selector: "a.virtual-tour, .tour-link"
        attribute: "href"
        transform:
          - type: "absolute_url"

      - name: "agent_info"
        selector: ".listing-agent, .agent-info"
        type: "complex"
        components:
          - name: "agent_name"
            selector: ".agent-name"
            type: "text"
          - name: "agent_phone"
            selector: ".agent-phone"
            type: "text"
            transform:
              - type: "normalize_phone"
          - name: "brokerage"
            selector: ".brokerage-name"
            type: "text"

      - name: "features"
        selector: ".property-features li, .amenities span"
        type: "list"
        transform:
          - type: "trim"
          - type: "deduplicate"

      - name: "school_district"
        selector: ".school-district, .schools"
        type: "text"

      - name: "hoa_fee"
        selector: ".hoa-fee, .association-fee"
        type: "text"
        transform:
          - type: "extract_number"

      - name: "property_tax"
        selector: ".property-tax, .annual-taxes"
        type: "text"
        transform:
          - type: "extract_number"

      - name: "listing_url"
        selector: "a.property-link, .details-link"
        attribute: "href"
        required: true
        transform:
          - type: "absolute_url"
          - type: "clean_tracking_params"

  # Pagination for search results
  - name: "pagination"
    type: "pagination"
    strategies:
      - type: "query_parameter"
        parameter: "page"
        start: 1
        increment: 1
        max_pages: 100
      - type: "result_count"
        selector: ".result-count, .total-results"
        per_page: 20

  # Map data extraction
  - name: "map_properties"
    type: "javascript"
    enabled: false
    script: |
      // Extract property data from map markers
      const markers = window.mapMarkers || [];
      return markers.map(marker => ({
        latitude: marker.lat,
        longitude: marker.lng,
        property_id: marker.id,
        price: marker.price
      }));

# Output configuration for real estate data
output:
  format: "json"
  path: "outputs/real-estate/${DATE}/${MARKET}_properties_${TIMESTAMP}.json"

  # Schema validation
  schema:
    required_fields: ["mls_number", "address", "price", "property_type"]
    unique_keys: ["mls_number"]

  # Enrichment
  enrich:
    - type: "geocoding"
      enabled: false
      service: "nominatim"
      fields: ["address.street", "address.city", "address.state"]
    - type: "market_analysis"
      calculate:
        - "median_price_per_sqft"
        - "average_days_on_market"
        - "price_trends"

# Market analysis configuration
analysis:
  enabled: true
  metrics:
    - name: "market_inventory"
      groupBy: ["property_type", "bedrooms"]
      calculate: ["count", "median_price", "average_price"]

    - name: "price_distribution"
      buckets: [100000, 200000, 300000, 500000, 750000, 1000000]

    - name: "new_listings"
      period: "daily"
      alert_threshold: 20  # Alert if more than 20 new listings

    - name: "price_changes"
      track: true
      alert_on_reduction: 5  # Alert on 5% price reduction

# Historical tracking
history:
  enabled: true
  storage: "database"
  retention_days: 365
  track_changes:
    - "price"
    - "status"
    - "days_on_market"

  snapshots:
    frequency: "daily"
    time: "06:00"

# Alerts and monitoring
monitoring:
  alerts:
    - type: "new_listing"
      criteria:
        price: "< 500000"
        bedrooms: ">= 3"
        property_type: "single_family"

    - type: "price_reduction"
      threshold: 10000

    - type: "status_change"
      from: "active"
      to: ["pending", "contingent"]

    - type: "hot_property"
      criteria:
        days_on_market: "< 3"
        price_per_sqft: "< market_average"

# Compliance for real estate data
compliance:
  mls_rules: true
  fair_housing: true
  data_accuracy: true
  refresh_frequency: 900  # 15 minutes
  attribution: "Listing data courtesy of ${MLS_NAME}"

# Export formats for real estate professionals
export:
  formats:
    - type: "mls_compatible"
      format: "csv"
      encoding: "utf-8"
      field_mapping: "configs/mls-field-mapping.json"

    - type: "crm_import"
      format: "xlsx"
      sheets:
        - name: "Properties"
          data: "listings"
        - name: "Market Analysis"
          data: "analytics"

    - type: "map_data"
      format: "geojson"
      coordinate_fields:
        lat: "latitude"
        lng: "longitude"
